version: "3.8"
services:

#here we specify all the containrs by mentioning the images
#then we mention the port of the image
#the first image we have is selenium hub and this will represent the hub node
  selenium-hub:
    image: selenium/hub
    ports:
      - 4442:4442
      - 4443:4443
      - 4444:4444
    environment:
      #here i say that i have a maximum of 16 browsers that could be running in the Grid
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 300
      GRID_TIMEOUT: 300
#here we will specificy the first node by specifiing the image
#then we mention on the depends on "selenium-hub" we do this to declare that this container will not be up and running
#before the "selenium-hub" container be up and running
  chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
       #below we say that we will only be running at maximum 2 browsers on this container
      - SE_NODE_MAX_SESSIONS=2




    # volumes:
    #   - /dev/shm:/dev/shm

  firefox:
    image: selenium/node-firefox
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=2
